# yml文件或者yaml文件
# 配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sirius00111?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 362880
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      # 配置deepseek的api-key,url
      api-key: sk-29386c87e34a4d6fa574f9a46e571a1a
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

# 默认端口号为：8080
server:
  port: 8080

# 配置mybatis的属性
mybatis:
  # 配置Mapper文件的位置(这里的classpath默认为resources包)
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 指定日志实现类(将sql语句输出到标准控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 启用MyBatis对数据库表字段(使用下划线命名)与Java类属性(使用驼峰命名)的自动转换.eg:user_name->userName
    map-underscore-to-camel-case: true